allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
  workerd: true
patchedDependencies:
  '@opennextjs/aws@4.1.4': patches/@opennextjs__aws@4.1.4.patch
  '@opennextjs/cloudflare@1.20.6': patches/@opennextjs__cloudflare@1.20.6.patch
